joint_limits:
  turntable_disc_joint:
    has_position_limits: true
    max_position: 3.1415
    min_position: -3.1415
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    max_effort: 150.0
  shoulder_pan_joint:
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    max_effort: 150.0
  shoulder_lift_joint:
    has_position_limits: true
    min_position: -2.0943951
    max_position: -1.04719755
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    max_effort: 150.0
  elbow_joint:
    has_position_limits: true
    min_position: 0.78539816
    max_position: 2.35619449
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    max_effort: 150.0
  wrist_1_joint:
    has_position_limits: true
    min_position: -3.14159265
    max_position: 0.0
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    max_effort: 150.0
  wrist_2_joint:
    has_position_limits: true
    min_position: -2.35619449
    max_position: -0.785398164
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    max_effort: 150.0
  wrist_3_joint:
    has_position_limits: true
    min_position: -1.57079633
    max_position: 1.57079633
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    max_effort: 150.0