# Default initial positions for inspection_cell's ros2_control fake system

initial_positions:
  shoulder_pan_joint: 0 # 3.14
  turntable_disc_joint: 0.0
  shoulder_lift_joint: -1.8398
  elbow_joint: -1.8224
  wrist_1_joint: -1.0
  wrist_2_joint: 1.57
  wrist_3_joint: 0.0