# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    # - ur5e_controller
    # - turntable_trajectory_controller
    - inspection_cell_controller

  ur5e_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

  turntable_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - turntable_disc_joint
    action_ns: follow_joint_trajectory
    default: true

  inspection_cell_controller:
    type: FollowJointTrajectory
    joints:
      - turntable_disc_joint
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    default: true
    action_ns: follow_joint_trajectory  