# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    inspection_cell_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    ur5e_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    turntable_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    inspection_cell_forward_position_controller:
      type: position_controllers/JointGroupPositionController
 
    turntable_forward_position_controller:
      type: position_controllers/JointGroupPositionController

    ur5e_forward_position_controller:
      type: position_controllers/JointGroupPositionController        

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

inspection_cell_controller:
  ros__parameters:
    joints:
      - turntable_disc_joint
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: true

ur5e_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

turntable_trajectory_controller:
  ros__parameters:
    joints:
      - turntable_disc_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

inspection_cell_forward_position_controller:
  ros__parameters:
    joint:
      - turntable_disc_joint  
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    interface_name: position  

turntable_forward_position_controller:
  ros__parameters:
    joints:
      - disc_joint
    interface_name: position

ur5e_forward_position_controller:
  ros__parameters:
    joints:  
      - shoulder_pan_joint      
      - shoulder_lift_joint       
      - elbow_joint            
      - wrist_1_joint          
      - wrist_2_joint          
      - wrist_3_joint          
    interface_name: position     