# Combined ros2_controllers.yaml for Inspection Cell
# Location: inspection_cell_description/config/cell_ros2_controllers.yaml
# This file combines UR5e and turntable controllers for the unified system

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # ====== JOINT STATE BROADCASTERS ======
    
    # Combined joint state broadcaster (publishes all 7 joints to /joint_states)
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # ====== UNIFIED SYSTEM CONTROLLERS ======
    
    # Primary controller for the complete 7-DOF inspection cell
    inspection_cell_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # Secondary controller for the complete 7-DOF inspection cell
    inspection_cell_forward_position_controller:
      type: position_controllers/JointGroupPositionController

    # ====== INDIVIDUAL SYSTEM CONTROLLERS (BACKUP/TESTING) ======
    
    # UR5e-only controller (6 DOF)
    ur5e_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # Turntable-only controller (1 DOF)
    turntable_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # Turntable-only controller (1 DOF)    
    turntable_forward_position_controller:
      type: position_controllers/JointGroupPositionController

    # Ur5e-only forward position controller (6 DOF)
    ur5e_forward_position_controller:
      type: position_controllers/JointGroupPositionController  
# ====== CONTROLLER CONFIGURATIONS ======

# Primary unified controller (7 DOF: turntable + UR5e)
inspection_cell_controller:
  ros__parameters:
    joints:
      - turntable_disc_joint    
      - shoulder_pan_joint      
      - shoulder_lift_joint       
      - elbow_joint            
      - wrist_1_joint          
      - wrist_2_joint          
      - wrist_3_joint          
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    allow_nonzero_velocity_at_trajectory_end: false

# Secondary unified controller (7 DOF: turntable + UR5e)
inspection_cell_forward_position_controller:
  ros__parameters:
    joints:
      - turntable_disc_joint    
      - shoulder_pan_joint      
      - shoulder_lift_joint       
      - elbow_joint            
      - wrist_1_joint          
      - wrist_2_joint          
      - wrist_3_joint          
    interface_name: position 

# UR5e-only controller (6 DOF)
ur5e_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    allow_nonzero_velocity_at_trajectory_end: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.6
      shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      elbow_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

# Turntable-only controller (1 DOF)
turntable_trajectory_controller:
  ros__parameters:
    joints:
      - turntable_disc_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    allow_nonzero_velocity_at_trajectory_end: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.6
      turntable_disc_joint: { trajectory: 0.1, goal: 0.05 }

# Turntable-only forward position controller (1 DOF)
turntable_forward_position_controller:
  ros__parameters:
    joints:
      - disc_joint
    interface_name: position

# Ur5e-only forward position controller (6 DOF)
ur5e_forward_position_controller:
  ros__parameters:
    joints:  
      - shoulder_pan_joint      
      - shoulder_lift_joint       
      - elbow_joint            
      - wrist_1_joint          
      - wrist_2_joint          
      - wrist_3_joint          
    interface_name: position       