# Combined ros2_controllers.yaml for Inspection Cell
# Location: inspection_cell_description/config/cell_ros2_controllers.yaml
# This file combines UR5e and turntable controllers for the unified system

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # ====== JOINT STATE BROADCASTERS ======
    
    # Combined joint state broadcaster (publishes all 7 joints to /joint_states)
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # ====== UNIFIED SYSTEM CONTROLLERS ======
    
    # Primary controller for the complete 7-DOF inspection cell
    inspection_cell_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # Secondary controller for the complete 7-DOF inspection cell
    inspection_cell_forward_position_controller:
      type: position_controllers/JointGroupPositionController

    # ====== INDIVIDUAL SYSTEM CONTROLLERS (BACKUP/TESTING) ======
    
    # UR5e-only controller (6 DOF)
    ur5e_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # Turntable-only controller (1 DOF)
    turntable_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # Turntable-only controller (1 DOF)    
    turntable_forward_position_controller:
      type: position_controllers/JointGroupPositionController

    # Ur5e-only forward position controller (6 DOF)
    ur5e_forward_position_controller:
      type: position_controllers/JointGroupPositionController  

    # DEFAULT CONTROLLERS FOR UR5e (FOR REFERENCE)
    io_and_status_controller:
      type: ur_controllers/GPIOController

    speed_scaling_state_broadcaster:
      type: ur_controllers/SpeedScalingStateBroadcaster

    force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    scaled_joint_trajectory_controller:
      type: ur_controllers/ScaledJointTrajectoryController

    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

    force_mode_controller:
      type: ur_controllers/ForceModeController

    freedrive_mode_controller:
      type: ur_controllers/FreedriveModeController

    passthrough_trajectory_controller:
      type: ur_controllers/PassthroughTrajectoryController

    tcp_pose_broadcaster:
      type: pose_broadcaster/PoseBroadcaster

    ur_configuration_controller:
      type: ur_controllers/URConfigurationController

    tool_contact_controller:
      type: ur_controllers/ToolContactController

    # The way this is currently implemented upstream doesn't really work for us. When using
    # position control, the robot will have a tracking error. However, limits will be enforced
    # from the currently reported position, effectively limiting the possible step size using the
    # joints' velocity limits. Until this is resolved, we will keep command limits non-enforced.
    # Note: On Jazzy this is the default behavior, anyway. For Rolling / Kilted this defaults to
    # true.
    enforce_command_limits: false
# ====== CONTROLLER CONFIGURATIONS ======

# Primary unified controller (7 DOF: turntable + UR5e)
inspection_cell_controller:
  ros__parameters:
    joints:
      - turntable_disc_joint    
      - shoulder_pan_joint      
      - shoulder_lift_joint       
      - elbow_joint            
      - wrist_1_joint          
      - wrist_2_joint          
      - wrist_3_joint          
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: true
    allow_nonzero_velocity_at_trajectory_end: false

# Secondary unified controller (7 DOF: turntable + UR5e)
inspection_cell_forward_position_controller:
  ros__parameters:
    joints:
      - turntable_disc_joint    
      - shoulder_pan_joint      
      - shoulder_lift_joint       
      - elbow_joint            
      - wrist_1_joint          
      - wrist_2_joint          
      - wrist_3_joint          
    interface_name: position 

# UR5e-only controller (6 DOF)
ur5e_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: false
    allow_nonzero_velocity_at_trajectory_end: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.6
      shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      elbow_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

# Turntable-only controller (1 DOF)
turntable_trajectory_controller:
  ros__parameters:
    joints:
      - turntable_disc_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: false
    allow_nonzero_velocity_at_trajectory_end: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.6
      turntable_disc_joint: { trajectory: 0.1, goal: 0.05 }

# Turntable-only forward position controller (1 DOF)
turntable_forward_position_controller:
  ros__parameters:
    joints:
      - turntable_disc_joint
    interface_name: position

# Ur5e-only forward position controller (6 DOF)
ur5e_forward_position_controller:
  ros__parameters:
    joints:  
      - shoulder_pan_joint      
      - shoulder_lift_joint       
      - elbow_joint            
      - wrist_1_joint          
      - wrist_2_joint          
      - wrist_3_joint          
    interface_name: position       

# ====== DEFAULT CONTROLLERS FOR UR5e (FOR REFERENCE) ======

speed_scaling_state_broadcaster:
  ros__parameters:
    state_publish_rate: 100.0
    tf_prefix: "$(var tf_prefix)"

io_and_status_controller:
  ros__parameters:
    tf_prefix: "$(var tf_prefix)"

ur_configuration_controller:
  ros__parameters:
    tf_prefix: "$(var tf_prefix)"

force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: $(var tf_prefix)tcp_fts_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: $(var tf_prefix)tool0
    topic_name: ft_data


joint_trajectory_controller:
  ros__parameters:
    joints:
      - $(var tf_prefix)shoulder_pan_joint
      - $(var tf_prefix)shoulder_lift_joint
      - $(var tf_prefix)elbow_joint
      - $(var tf_prefix)wrist_1_joint
      - $(var tf_prefix)wrist_2_joint
      - $(var tf_prefix)wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      $(var tf_prefix)shoulder_pan_joint: {trajectory: 0.2, goal: 0.1}
      $(var tf_prefix)shoulder_lift_joint: {trajectory: 0.2, goal: 0.1}
      $(var tf_prefix)elbow_joint: {trajectory: 0.2, goal: 0.1}
      $(var tf_prefix)wrist_1_joint: {trajectory: 0.2, goal: 0.1}
      $(var tf_prefix)wrist_2_joint: {trajectory: 0.2, goal: 0.1}
      $(var tf_prefix)wrist_3_joint: {trajectory: 0.2, goal: 0.1}
    speed_scaling:
      state_interface: $(var tf_prefix)speed_scaling/speed_scaling_factor
      # Setting the command interface currently would clash with the io_and_status_controller
      # This will probably be changed in the future.
      # command_interface: $(var tf_prefix)speed_scaling/target_speed_fraction_cmd


scaled_joint_trajectory_controller:
  ros__parameters:
    joints:
      - $(var tf_prefix)shoulder_pan_joint
      - $(var tf_prefix)shoulder_lift_joint
      - $(var tf_prefix)elbow_joint
      - $(var tf_prefix)wrist_1_joint
      - $(var tf_prefix)wrist_2_joint
      - $(var tf_prefix)wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      $(var tf_prefix)shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      $(var tf_prefix)shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      $(var tf_prefix)elbow_joint: { trajectory: 0.2, goal: 0.1 }
      $(var tf_prefix)wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      $(var tf_prefix)wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      $(var tf_prefix)wrist_3_joint: { trajectory: 0.2, goal: 0.1 }
    speed_scaling_interface_name: $(var tf_prefix)speed_scaling/speed_scaling_factor

passthrough_trajectory_controller:
  ros__parameters:
    tf_prefix: "$(var tf_prefix)"
    joints:
      - $(var tf_prefix)shoulder_pan_joint
      - $(var tf_prefix)shoulder_lift_joint
      - $(var tf_prefix)elbow_joint
      - $(var tf_prefix)wrist_1_joint
      - $(var tf_prefix)wrist_2_joint
      - $(var tf_prefix)wrist_3_joint
    state_interfaces:
      - position
      - velocity
    speed_scaling_interface_name: $(var tf_prefix)speed_scaling/speed_scaling_factor

forward_velocity_controller:
  ros__parameters:
    joints:
      - $(var tf_prefix)shoulder_pan_joint
      - $(var tf_prefix)shoulder_lift_joint
      - $(var tf_prefix)elbow_joint
      - $(var tf_prefix)wrist_1_joint
      - $(var tf_prefix)wrist_2_joint
      - $(var tf_prefix)wrist_3_joint
    interface_name: velocity

force_mode_controller:
  ros__parameters:
    tf_prefix: "$(var tf_prefix)"

freedrive_mode_controller:
  ros__parameters:
    tf_prefix: "$(var tf_prefix)"

tcp_pose_broadcaster:
  ros__parameters:
    frame_id: $(var tf_prefix)base
    pose_name: $(var tf_prefix)tcp_pose
    tf:
      child_frame_id: $(var tf_prefix)tool0_controller

tool_contact_controller:
  ros__parameters:
    tf_prefix: "$(var tf_prefix)"