controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    inspection_cell_controllerv1:
      type: joint_trajectory_controller/JointTrajectoryController

    ur5e_controllerv1:
      type: joint_trajectory_controller/JointTrajectoryController

    turntable_trajectory_controllerv1:
      type: joint_trajectory_controller/JointTrajectoryController

inspection_cell_controllerv1:
  ros__parameters:
    joints:
      - turntable_disc_joint    
      - shoulder_pan_joint      
      - shoulder_lift_joint       
      - elbow_joint            
      - wrist_1_joint          
      - wrist_2_joint          
      - wrist_3_joint          
    command_interfaces:
      - position
      - velocity
      - acceleration
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    allow_nonzero_velocity_at_trajectory_end: false

# UR5e-only controller (6 DOF)
ur5e_controllerv1:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    allow_nonzero_velocity_at_trajectory_end: false

turntable_trajectory_controllerv1:
  ros__parameters:
    joints:
      - turntable_disc_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    allow_nonzero_velocity_at_trajectory_end: false

