# Combined ros2_controllers.yaml for Inspection Cell
# Location: inspection_cell_description/config/cell_ros2_controllers.yaml
# This file combines UR5e and turntable controllers for the unified system

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # ====== JOINT STATE BROADCASTERS ======
    
    # Combined joint state broadcaster (publishes all 7 joints to /joint_states)
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # ====== UNIFIED SYSTEM CONTROLLERS (PRIMARY) ======
    
    # Main controller for the complete 7-DOF inspection cell
    inspection_cell_controllerv1:
      type: joint_trajectory_controller/JointTrajectoryController

    # ====== INDIVIDUAL SYSTEM CONTROLLERS (BACKUP/TESTING) ======
    
    # UR5e-only controller (6 DOF)
    ur5e_controllerv1:
      type: joint_trajectory_controller/JointTrajectoryController

    # Turntable-only controller (1 DOF)
    turntable_trajectory_controllerv1:
      type: joint_trajectory_controller/JointTrajectoryController

    # # ====== UR-SPECIFIC CONTROLLERS ======
    
    # # IO and status controller for UR robot
    # io_and_status_controller:
    #   type: ur_controllers/GPIOController

    # # Speed scaling state broadcaster for UR robot
    # speed_scaling_state_broadcaster:
    #   type: ur_controllers/SpeedScalingStateBroadcaster

    # # Force/torque sensor broadcaster for UR robot
    # force_torque_sensor_broadcaster:
    #   type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    # # Scaled joint trajectory controller (UR-specific with speed scaling)
    # scaled_joint_trajectory_controller:
    #   type: ur_controllers/ScaledJointTrajectoryController

    # # Forward controllers for individual joint control
    # forward_velocity_controller:
    #   type: velocity_controllers/JointGroupVelocityController

    # forward_position_controller:
    #   type: position_controllers/JointGroupPositionController

# ====== CONTROLLER CONFIGURATIONS ======

# Primary unified controller (7 DOF: turntable + UR5e)
inspection_cell_controllerv1:
  ros__parameters:
    joints:
      - turntable_disc_joint    
      - shoulder_pan_joint      
      - shoulder_lift_joint       
      - elbow_joint            
      - wrist_1_joint          
      - wrist_2_joint          
      - wrist_3_joint          
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    allow_nonzero_velocity_at_trajectory_end: false
    # constraints:
    #   stopped_velocity_tolerance: 0.01
    #   goal_time: 0.6
    #   turntable_disc_joint: { trajectory: 0.0, goal: 0.0 }
    #   shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
    #   shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
    #   elbow_joint: { trajectory: 0.2, goal: 0.1 }
    #   wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
    #   wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
    #   wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

# UR5e-only controller (6 DOF)
ur5e_controllerv1:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    allow_nonzero_velocity_at_trajectory_end: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.6
      shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      elbow_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

# Turntable-only controller (1 DOF)
turntable_trajectory_controllerv1:
  ros__parameters:
    joints:
      - turntable_disc_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    allow_nonzero_velocity_at_trajectory_end: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.6
      turntable_disc_joint: { trajectory: 0.1, goal: 0.05 }

# # UR-specific scaled trajectory controller
# scaled_joint_trajectory_controller:
#   ros__parameters:
#     joints:
#       - shoulder_pan_joint
#       - shoulder_lift_joint
#       - elbow_joint
#       - wrist_1_joint
#       - wrist_2_joint
#       - wrist_3_joint
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity
#     state_publish_rate: 50.0
#     action_monitor_rate: 20.0
#     allow_partial_joints_goal: false
#     allow_nonzero_velocity_at_trajectory_end: false
#     constraints:
#       stopped_velocity_tolerance: 0.01
#       goal_time: 0.6
#       shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
#       shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
#       elbow_joint: { trajectory: 0.2, goal: 0.1 }
#       wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
#       wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
#       wrist_3_joint: { trajectory: 0.2, goal: 0.1 }
#     speed_scaling_interface_name: speed_scaling/speed_scaling_factor

# # UR-specific controllers
# io_and_status_controller:
#   ros__parameters:
#     tf_prefix: ""
#     state_publish_rate: 50.0

# speed_scaling_state_broadcaster:
#   ros__parameters:
#     state_publish_rate: 100.0
#     tf_prefix: ""

# force_torque_sensor_broadcaster:
#   ros__parameters:
#     sensor_name: tcp_fts_sensor
#     state_interface_names:
#       - force.x
#       - force.y  
#       - force.z
#       - torque.x
#       - torque.y
#       - torque.z
#     frame_id: tool0
#     topic_name: ft_sensor_readings

# # Forward controllers for individual joint control
# forward_velocity_controller:
#   ros__parameters:
#     joints:
#       - turntable_disc_joint
#       - shoulder_pan_joint
#       - shoulder_lift_joint
#       - elbow_joint
#       - wrist_1_joint
#       - wrist_2_joint
#       - wrist_3_joint
#     interface_name: velocity

# forward_position_controller:
#   ros__parameters:
#     joints:
#       - turntable_disc_joint
#       - shoulder_pan_joint
#       - shoulder_lift_joint
#       - elbow_joint
#       - wrist_1_joint
#       - wrist_2_joint
#       - wrist_3_joint
#     interface_name: position  