joint_limits:
  turntable_disc_joint:
    has_position_limits: true
    max_position: 100000
    min_position: -100000
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    max_effort: 150.0
  shoulder_pan_joint:
    has_position_limits: true
    max_position: 0
    min_position: 1.57
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    max_effort: 150.0
  shoulder_lift_joint:
    has_position_limits: true
    max_position: -1.57
    min_position: 0
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    max_effort: 150.0
  elbow_joint:
    has_position_limits: true
    max_position: 0.785
    min_position: 2.356
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    max_effort: 150.0
  wrist_1_joint:
    has_position_limits: true
    max_position: 3.927
    min_position: 5.498
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    max_effort: 150.0
  wrist_2_joint:
    has_position_limits: true
    max_position: -2.356
    min_position: -0.785
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    max_effort: 150.0
  wrist_3_joint:
    has_position_limits: true
    max_position: -3.142
    min_position: 0
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    max_effort: 150.0